# Generated by Django 4.0.3 on 2022-03-16 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('format', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('overall_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Match_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(help_text='Enter 0 for upcoming and 1 for completed')),
            ],
        ),
        migrations.CreateModel(
            name='Sport_League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.format')),
                ('hostels', models.ManyToManyField(to='spardha.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.format')),
                ('hostels', models.ManyToManyField(to='spardha.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel', to='spardha.hostel')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.match_all')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spardha.hostel')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('hostel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='spardha.hostel')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
            ],
        ),
        migrations.AddField(
            model_name='match_all',
            name='round',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.stage'),
        ),
        migrations.AddField(
            model_name='match_all',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.sport'),
        ),
        migrations.AddField(
            model_name='match_all',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.status'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('score1', models.IntegerField(blank=True, null=True)),
                ('score2', models.IntegerField(blank=True, null=True)),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.stage')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.status')),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='spardha.hostel')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='spardha.hostel')),
            ],
        ),
    ]
