# Generated by Django 4.0.3 on 2022-03-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='hostels',
        ),
        migrations.AddField(
            model_name='score',
            name='hostel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel', to='spardha.hostel'),
        ),
        migrations.AlterField(
            model_name='point',
            name='hostels',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='spardha.hostel'),
        ),
    ]
