# Generated by Django 4.0.3 on 2022-03-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Format',
        ),
        migrations.RemoveField(
            model_name='matchd',
            name='hostels',
        ),
        migrations.AlterField(
            model_name='sport',
            name='format',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C'), (4, 'D')], help_text='A - Football, Hockey, Cricket, Khokho, Basketball, Water Polo.  B - Lawn Tennis, Volleyball. C - Badminton, Table Tennis, Squash. D - Rest everything'),
        ),
    ]
