# Generated by Django 4.0.3 on 2022-03-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_all',
            name='scores',
        ),
    ]
