# Generated by Django 4.0.3 on 2022-03-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0002_remove_sport_league_format_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.BooleanField(default=False, help_text='Enter 0 for upcoming and 1 for completed'),
        ),
        migrations.AlterField(
            model_name='match_all',
            name='status',
            field=models.BooleanField(default=False, help_text='Enter 0 for upcoming and 1 for completed'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
