# Generated by Django 4.0.3 on 2022-03-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0002_remove_match_all_scores_match_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_set',
            name='format',
        ),
        migrations.RemoveField(
            model_name='match_set',
            name='score1',
        ),
        migrations.RemoveField(
            model_name='match_set',
            name='score2',
        ),
        migrations.RemoveField(
            model_name='match_set',
            name='set',
        ),
        migrations.AddField(
            model_name='match_set',
            name='format1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='format2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='format3',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='format4',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='format5',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='game1_score1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='game1_score2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='game2_score1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='game2_score2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='game3_score1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='game3_score2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='game4_score1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='game4_score2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='game5_score1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match_set',
            name='game5_score2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
