# Generated by Django 4.0.3 on 2022-03-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0003_alter_set_score_team1_game1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='score_team1_game1',
            new_name='team1_game1',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='score_team1_game2',
            new_name='team1_game2',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='score_team1_game3',
            new_name='team1_game3',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='score_team1_game4',
            new_name='team1_game4',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='score_team1_game5',
            new_name='team1_game5',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='score_team2_game1',
            new_name='team2_game1',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='score_team2_game2',
            new_name='team2_game2',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='score_team2_game3',
            new_name='team2_game3',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='score_team2_game4',
            new_name='team2_game4',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='score_team2_game5',
            new_name='team2_game5',
        ),
    ]
