# Generated by Django 4.0.3 on 2022-03-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0003_stage_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='overall_points',
            field=models.IntegerField(default=0),
        ),
    ]
