# Generated by Django 4.0.3 on 2022-03-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0003_alter_match_status_alter_match_all_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='point',
            unique_together={('hostel', 'sport')},
        ),
    ]
