# Generated by Django 4.0.3 on 2022-03-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0003_remove_match_set_format_remove_match_set_score1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_set',
            name='game1_score1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='game1_score2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='game2_score1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='game2_score2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='game3_score1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='game3_score2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='game4_score1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='game4_score2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='game5_score1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='game5_score2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
