# Generated by Django 4.0.3 on 2022-03-13 05:54

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0004_alter_hostel_overall_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport_League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standings', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('final_points', models.IntegerField()),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.format')),
                ('hostels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('final_points', models.IntegerField()),
                ('format', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.format')),
                ('hostels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Match_all',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('scores', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('points_awarded', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
                ('round', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.stage')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.status')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('score1', models.IntegerField()),
                ('score2', models.IntegerField()),
                ('points1', models.IntegerField()),
                ('points2', models.IntegerField()),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.stage')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.status')),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='spardha.hostel')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='spardha.hostel')),
            ],
        ),
    ]
