# Generated by Django 4.0.3 on 2022-03-17 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0004_alter_point_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='match_all',
            name='hostels',
            field=models.ManyToManyField(to='spardha.hostel'),
        ),
    ]
