# Generated by Django 4.0.3 on 2022-03-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0004_alter_match_set_game1_score1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_set',
            name='winner',
            field=models.IntegerField(blank=True, choices=[(1, 'team1'), (2, 'team2')], null=True),
        ),
    ]
