# Generated by Django 4.0.3 on 2022-03-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0005_sport_league_sport_match_all_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='hostels',
        ),
        migrations.AddField(
            model_name='sport',
            name='hostels',
            field=models.ManyToManyField(null=True, to='spardha.hostel'),
        ),
    ]
