# Generated by Django 4.0.3 on 2022-03-23 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0005_alter_match_set_winner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, help_text='Enter 0 for upcoming and 1 for completed')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('score1', models.CharField(blank=True, max_length=15, null=True)),
                ('score2', models.CharField(blank=True, max_length=15, null=True)),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.stage')),
            ],
        ),
        migrations.CreateModel(
            name='MatchB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, help_text='Enter 0 for upcoming and 1 for completed')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.stage')),
            ],
        ),
        migrations.RenameModel(
            old_name='Match_all',
            new_name='MatchD',
        ),
        migrations.AddField(
            model_name='hostel',
            name='type',
            field=models.IntegerField(choices=[(1, 'Boys'), (2, 'Girls')], null=True),
        ),
        migrations.AlterField(
            model_name='format',
            name='format',
            field=models.CharField(help_text='A - Football, Hockey, Cricket, Khokho, Basketball, Water Polo.  B - Lawn Tennis, Volleyball. C - Badminton, Table Tennis, Squash. D - Rest everything', max_length=10),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='spardha.hostel'),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='spardha.hostel'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.AddField(
            model_name='matchb',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player1', to='spardha.hostel'),
        ),
        migrations.AddField(
            model_name='matchb',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player2', to='spardha.hostel'),
        ),
        migrations.AddField(
            model_name='matcha',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team1', to='spardha.hostel'),
        ),
        migrations.AddField(
            model_name='matcha',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team2', to='spardha.hostel'),
        ),
    ]
