# Generated by Django 4.0.3 on 2022-03-17 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0005_match_all_hostels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='sport',
        ),
    ]
