# Generated by Django 4.0.3 on 2022-03-14 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0006_remove_sport_hostels_sport_hostels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spardha.hostel')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
            ],
        ),
    ]
