# Generated by Django 4.0.3 on 2022-03-23 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0006_matcha_matchb_rename_match_all_matchd_hostel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team1', models.CharField(blank=True, max_length=15, null=True)),
                ('score_team2', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='matchb',
            name='set1',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set1', to='spardha.set'),
        ),
        migrations.AddField(
            model_name='matchb',
            name='set2',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set2', to='spardha.set'),
        ),
        migrations.AddField(
            model_name='matchb',
            name='set3',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set3', to='spardha.set'),
        ),
        migrations.AddField(
            model_name='matchb',
            name='set4',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set4', to='spardha.set'),
        ),
        migrations.AddField(
            model_name='matchb',
            name='set5',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='set5', to='spardha.set'),
        ),
    ]
