# Generated by Django 4.0.3 on 2022-03-14 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0006_remove_sport_hostels_sport_hostels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='final_points',
            field=models.IntegerField(blank=True),
        ),
    ]
