# Generated by Django 4.0.3 on 2022-03-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0006_remove_score_sport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='match_all',
            name='date_time',
        ),
        migrations.AddField(
            model_name='match',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='match_all',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='match_all',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
