# Generated by Django 4.0.3 on 2022-03-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0007_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Score',
            new_name='Points',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='score',
            new_name='points',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='points2',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='final_points',
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.IntegerField(default=0),
        ),
    ]
