# Generated by Django 4.0.3 on 2022-03-14 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0007_alter_sport_final_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='final_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
