# Generated by Django 4.0.3 on 2022-03-23 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0007_set_matchb_set1_matchb_set2_matchb_set3_matchb_set4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchb',
            name='set1',
        ),
        migrations.RemoveField(
            model_name='matchb',
            name='set2',
        ),
        migrations.RemoveField(
            model_name='matchb',
            name='set3',
        ),
        migrations.RemoveField(
            model_name='matchb',
            name='set4',
        ),
        migrations.RemoveField(
            model_name='matchb',
            name='set5',
        ),
        migrations.AddField(
            model_name='set',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.matchb'),
        ),
    ]
