# Generated by Django 4.0.3 on 2022-03-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0008_remove_matchb_set1_remove_matchb_set2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchb',
            name='winner',
            field=models.IntegerField(blank=True, choices=[(1, 'team1'), (2, 'team2')], null=True),
        ),
    ]
