# Generated by Django 4.0.3 on 2022-03-14 08:41

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0008_alter_sport_final_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport_league',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='final_points',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='sport',
            name='hostels',
            field=models.ManyToManyField(to='spardha.hostel'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sport_league',
            name='final_points',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict, null=True),
        ),
        migrations.RemoveField(
            model_name='sport_league',
            name='hostels',
        ),
        migrations.AddField(
            model_name='sport_league',
            name='hostels',
            field=models.ManyToManyField(to='spardha.hostel'),
        ),
    ]
