# Generated by Django 4.0.3 on 2022-03-23 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0009_matchb_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match_set',
            name='team1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P1', to='spardha.hostel'),
        ),
        migrations.AlterField(
            model_name='match_set',
            name='team2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='P2', to='spardha.hostel'),
        ),
        migrations.CreateModel(
            name='MatchC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False, help_text='Enter 0 for upcoming and 1 for completed')),
                ('date', models.DateField(null=True)),
                ('time', models.TimeField(null=True)),
                ('winner', models.IntegerField(blank=True, choices=[(1, 'team1'), (2, 'team2')], null=True)),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.stage')),
                ('team1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p1', to='spardha.hostel')),
                ('team2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='p2', to='spardha.hostel')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField()),
                ('score_team1', models.CharField(blank=True, max_length=15, null=True)),
                ('score_team2', models.CharField(blank=True, max_length=15, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.matchc')),
            ],
        ),
    ]
