# Generated by Django 4.0.3 on 2022-03-23 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0010_alter_match_set_team1_alter_match_set_team2_matchc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game_set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_number', models.IntegerField(blank=True, null=True)),
                ('score_team1', models.CharField(blank=True, max_length=15, null=True)),
                ('score_team2', models.CharField(blank=True, max_length=15, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.matchc')),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
