# Generated by Django 4.0.3 on 2022-03-23 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0011_game_set_delete_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game_set',
            name='game_number',
        ),
        migrations.RemoveField(
            model_name='game_set',
            name='match',
        ),
        migrations.RemoveField(
            model_name='set',
            name='score_team1',
        ),
        migrations.RemoveField(
            model_name='set',
            name='score_team2',
        ),
        migrations.AddField(
            model_name='game_set',
            name='set',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.set'),
        ),
        migrations.AddField(
            model_name='set',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='g', to='spardha.game_set'),
        ),
        migrations.AddField(
            model_name='set',
            name='set_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='spardha.matchc'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_team1', models.CharField(blank=True, max_length=15, null=True)),
                ('score_team2', models.CharField(blank=True, max_length=15, null=True)),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.matchb')),
            ],
        ),
    ]
