# Generated by Django 4.0.3 on 2022-03-23 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0012_remove_game_set_game_number_remove_game_set_match_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='game',
        ),
    ]
