# Generated by Django 4.0.3 on 2022-03-14 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0008_rename_score_points_rename_score_points_points_and_more'),
        ('spardha', '0012_alter_match_points1_alter_match_points2_and_more'),
    ]

    operations = [
    ]
