# Generated by Django 4.0.3 on 2022-03-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0013_remove_set_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_set',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.matchc'),
        ),
    ]
