# Generated by Django 4.0.3 on 2022-03-14 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0013_merge_20220314_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_all',
            name='points_awarded',
        ),
        migrations.RemoveField(
            model_name='match_all',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='sport_league',
            name='standings',
        ),
        migrations.AddField(
            model_name='sport',
            name='final_points',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='score2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.BooleanField(help_text='Enter 0 for upcoming and 1 for completed'),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('hostels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.hostel')),
                ('match', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.match_all')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('hostels', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.hostel')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spardha.sport')),
            ],
        ),
    ]
