# Generated by Django 4.0.3 on 2022-03-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0014_game_set_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='set_name',
        ),
        migrations.AddField(
            model_name='set',
            name='game1',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='set',
            name='game2',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='set',
            name='game3',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='set',
            name='game4',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='set',
            name='game5',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='set',
            name='score_team1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='score_team2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Game_set',
        ),
    ]
