# Generated by Django 4.0.3 on 2022-03-23 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0015_remove_set_set_name_set_game1_set_game2_set_game3_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='score_team1',
            new_name='score_team1_game1',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='score_team2',
            new_name='score_team1_game2',
        ),
        migrations.AddField(
            model_name='set',
            name='score_team1_game3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='score_team1_game4',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='score_team1_game5',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='score_team2_game1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='score_team2_game2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='score_team2_game3',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='score_team2_game4',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='set',
            name='score_team2_game5',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
