# Generated by Django 4.0.3 on 2022-03-23 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0016_rename_score_team1_set_score_team1_game1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='set',
            name='game1',
        ),
        migrations.RemoveField(
            model_name='set',
            name='game2',
        ),
        migrations.RemoveField(
            model_name='set',
            name='game3',
        ),
        migrations.RemoveField(
            model_name='set',
            name='game4',
        ),
        migrations.RemoveField(
            model_name='set',
            name='game5',
        ),
        migrations.AddField(
            model_name='set',
            name='name',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
