# Generated by Django 4.0.3 on 2022-03-24 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spardha', '0017_remove_set_game1_remove_set_game2_remove_set_game3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
